CREATE TABLE Member (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	password VARCHAR(200) NOT NULL,
	salt VARCHAR(50) NOT NULL
);

CREATE TABLE Team (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	permissions INTEGER NOT NULL
);

CREATE TABLE MemberTeam (
	member INTEGER REFERENCES Member(id),
	team INTEGER REFERENCES Team(id)
);

CREATE TABLE Category (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE Area (
	id SERIAL PRIMARY KEY,
	category INTEGER REFERENCES Category(id),
	name VARCHAR(50) NOT NULL
);

CREATE TABLE Topic (
	id SERIAL PRIMARY KEY,
	area INTEGER REFERENCES Area(id),
	member INTEGER REFERENCES Member(id),
	name VARCHAR(50) NOT NULL
);

CREATE TABLE Message (
	id SERIAL PRIMARY KEY,
	topic INTEGER REFERENCES Topic(id),
	member INTEGER REFERENCES Member(id)
);

CREATE TABLE Version (
	id SERIAL PRIMARY KEY,
	message INTEGER REFERENCES Message(id),
        member INTEGER REFERENCES Member(id),
	title VARCHAR(50) NOT NULL,
	content VARCHAR(3000) NOT NULL,
	time TIMESTAMP WITH TIME ZONE NOT NULL
);